name: ansi_escape_codes
description: Yet another package for using ANSI escape codes and analyzing strings containing the escape codes.
version: 2.0.1
homepage: https://github.com/vi-k/ansi_escape_codes

environment:
  sdk: ^3.3.4

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
